create type "public"."gender" as enum ('male', 'female', 'other');

create table "public"."adherents" (
    "id" uuid not null default gen_random_uuid(),
    "first_name" text not null,
    "last_name" text not null,
    "birth_date" date not null,
    "gender" gender,
    "started_at" date,
    "registered_at" date,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."adherents" enable row level security;

create table "public"."adherents_grades" (
    "adherent_id" uuid not null,
    "grade_id" integer not null,
    "date" date
);


alter table "public"."adherents_grades" enable row level security;

create table "public"."grades" (
    "name" character varying not null,
    "id" integer generated by default as identity not null
);


alter table "public"."grades" enable row level security;

CREATE UNIQUE INDEX adherents_grades_pkey ON public.adherents_grades USING btree (adherent_id, grade_id);

CREATE UNIQUE INDEX adherents_id_key ON public.adherents USING btree (id);

CREATE UNIQUE INDEX adherents_pkey ON public.adherents USING btree (id);

CREATE UNIQUE INDEX grade_id_key ON public.grades USING btree (id);

CREATE UNIQUE INDEX grade_pkey ON public.grades USING btree (id);

alter table "public"."adherents" add constraint "adherents_pkey" PRIMARY KEY using index "adherents_pkey";

alter table "public"."adherents_grades" add constraint "adherents_grades_pkey" PRIMARY KEY using index "adherents_grades_pkey";

alter table "public"."grades" add constraint "grade_pkey" PRIMARY KEY using index "grade_pkey";

alter table "public"."adherents" add constraint "adherents_id_key" UNIQUE using index "adherents_id_key";

alter table "public"."adherents_grades" add constraint "adherents_grades_adherent_id_fkey" FOREIGN KEY (adherent_id) REFERENCES adherents(id) ON DELETE CASCADE not valid;

alter table "public"."adherents_grades" validate constraint "adherents_grades_adherent_id_fkey";

alter table "public"."adherents_grades" add constraint "adherents_grades_grade_id_fkey" FOREIGN KEY (grade_id) REFERENCES grades(id) not valid;

alter table "public"."adherents_grades" validate constraint "adherents_grades_grade_id_fkey";

alter table "public"."grades" add constraint "grade_id_key" UNIQUE using index "grade_id_key";

grant delete on table "public"."adherents" to "anon";

grant insert on table "public"."adherents" to "anon";

grant references on table "public"."adherents" to "anon";

grant select on table "public"."adherents" to "anon";

grant trigger on table "public"."adherents" to "anon";

grant truncate on table "public"."adherents" to "anon";

grant update on table "public"."adherents" to "anon";

grant delete on table "public"."adherents" to "authenticated";

grant insert on table "public"."adherents" to "authenticated";

grant references on table "public"."adherents" to "authenticated";

grant select on table "public"."adherents" to "authenticated";

grant trigger on table "public"."adherents" to "authenticated";

grant truncate on table "public"."adherents" to "authenticated";

grant update on table "public"."adherents" to "authenticated";

grant delete on table "public"."adherents" to "service_role";

grant insert on table "public"."adherents" to "service_role";

grant references on table "public"."adherents" to "service_role";

grant select on table "public"."adherents" to "service_role";

grant trigger on table "public"."adherents" to "service_role";

grant truncate on table "public"."adherents" to "service_role";

grant update on table "public"."adherents" to "service_role";

grant delete on table "public"."adherents_grades" to "anon";

grant insert on table "public"."adherents_grades" to "anon";

grant references on table "public"."adherents_grades" to "anon";

grant select on table "public"."adherents_grades" to "anon";

grant trigger on table "public"."adherents_grades" to "anon";

grant truncate on table "public"."adherents_grades" to "anon";

grant update on table "public"."adherents_grades" to "anon";

grant delete on table "public"."adherents_grades" to "authenticated";

grant insert on table "public"."adherents_grades" to "authenticated";

grant references on table "public"."adherents_grades" to "authenticated";

grant select on table "public"."adherents_grades" to "authenticated";

grant trigger on table "public"."adherents_grades" to "authenticated";

grant truncate on table "public"."adherents_grades" to "authenticated";

grant update on table "public"."adherents_grades" to "authenticated";

grant delete on table "public"."adherents_grades" to "service_role";

grant insert on table "public"."adherents_grades" to "service_role";

grant references on table "public"."adherents_grades" to "service_role";

grant select on table "public"."adherents_grades" to "service_role";

grant trigger on table "public"."adherents_grades" to "service_role";

grant truncate on table "public"."adherents_grades" to "service_role";

grant update on table "public"."adherents_grades" to "service_role";

grant delete on table "public"."grades" to "anon";

grant insert on table "public"."grades" to "anon";

grant references on table "public"."grades" to "anon";

grant select on table "public"."grades" to "anon";

grant trigger on table "public"."grades" to "anon";

grant truncate on table "public"."grades" to "anon";

grant update on table "public"."grades" to "anon";

grant delete on table "public"."grades" to "authenticated";

grant insert on table "public"."grades" to "authenticated";

grant references on table "public"."grades" to "authenticated";

grant select on table "public"."grades" to "authenticated";

grant trigger on table "public"."grades" to "authenticated";

grant truncate on table "public"."grades" to "authenticated";

grant update on table "public"."grades" to "authenticated";

grant delete on table "public"."grades" to "service_role";

grant insert on table "public"."grades" to "service_role";

grant references on table "public"."grades" to "service_role";

grant select on table "public"."grades" to "service_role";

grant trigger on table "public"."grades" to "service_role";

grant truncate on table "public"."grades" to "service_role";

grant update on table "public"."grades" to "service_role";
