name: Continuous Integration
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Format
      - run: pnpm run format

      - name: Lint
      - run: pnpm run lint

      - name: Type check
      - run: pnpm run type-check
